# Maintainer : Ajeet Kumar

**Practical machine learning with tensorflow week3 programming solution 2020**

Q1. Given a tensor t, load the tensor into a tensorflow’s tf.data.Dataset and run the reduce operation with parameters ​ initial_state = -1​ and ​ reduce_func = lambda x, y: x + y​ on the dataset. Choose the result of the operations from the options below: t =​ ​ [[3, 4, 2, 5, -2, 9, 5], [5, -4, 3, 6, -7, 0, 6], [8, 1, 7, -2, 6, 3, 0]]

In [17]:
import tensorflow as tf

In [18]:
#Define your tensor
t = tf.data.Dataset.from_tensor_slices([[3, 4, 2, 5, -2, 9, 5], [5, -4, 3, 6, -7, 0, 6], [8, 1, 7, -2, 6, 3, 0]]) 

In [20]:
# Reduce it by passing parameters
print('Answer of Q1 is ',t.reduce(-1, lambda x, y: x + y).numpy())


Answer of Q1 is  [15  0 11  8 -4 11 10]


Q2. Using the same tensor from Q1, we load the tensor into a tensorflow’s tf.data.Dataset and run the map operation with ​ map_func = lambda x: (x - tf.reduce_mean(x))​ . We then run the reduce operation with parameters initial_state = -3​ and reduce_func = lambda x, y: 3*x - 4*y​ on the dataset. Choose the result of the operations from the options below:

In [21]:
#Define your tensor
t = tf.data.Dataset.from_tensor_slices([[3, 4, 2, 5, -2, 9, 5], [5, -4, 3, 6, -7, 0, 6], [8, 1, 7, -2, 6, 3, 0]]) 

In [23]:
# First map and visualize answer
t = t.map(lambda x: (x-tf.reduce_mean(x)))
list(t.as_numpy_iterator())


[array([ 0,  1, -1,  2, -5,  6,  2], dtype=int32),
 array([ 4, -5,  2,  5, -8, -1,  5], dtype=int32),
 array([ 5, -2,  4, -5,  3,  0, -3], dtype=int32)]

In [24]:
# Reduce and print the answer
print('Answer of Q2 is :', t.reduce(-3, lambda x, y: 3*x - 4*y).numpy())

Answer of Q2 is : [-149  -49  -85 -193  183 -285 -201]


Q.5 and Q =.6 We are building a two layer neural network with 8 units in the input layer, 4 units in the hidden layer and 1 unit in the output layer. The hidden layer uses ReLU activation and the output layer uses sigmoid activation. Find below the weights and biases of the network. wij is the weight of the jth unit in the ith layer. The bias terms b and output terms o follow the same pattern.

					  w11=[−0.05,0.1,0.15,0.2,0.35,0.6,−0.9,−0.1]b11=0.8w12=[−0.5,0.1,0.1,−0.02,0.3,0.36,0.9,0.1]b12=−0.6w13=[−0.05,−0.15,0.1,0.2,0.35,−0.6,0.9,−0.1]b13=0.5w14=[−0.25,0.1,0.1,0.02,0.3,0.36,−0.9,0.1] b14=−0.1

	   Given input x=[1.1,0.2,0.4,−0.9,1.2,0.5,0.6,0.3], what are the outputs (rounded) of the hidden layer

In [26]:
# import required dependencies
import math
import numpy as np

# Define sigmoid and relu function
def sigmoid(x):
    return 1 / (1 + math.exp(-x))
def relu(x):
    return np.maximum(x, 0)

# Enter the input matrix
x = np.array([1.1,0.2,0.4,-0.9,1.2,0.5,0.6,0.3])

# Enter the weight and bias
w11 = np.array([-0.05,0.1,0.15,0.2,0.35,0.6,-0.9,-0.1])
b11 = 0.8
w12 = np.array([-0.5,0.1,0.1,-0.02,0.3,0.36,0.9,0.1])
b12 = -0.6
w13 = np.array([-0.05,-0.15,0.1, 0.2, 0.35, -0.6, 0.9,-0.1])
b13 = 0.5
w14 = np.array([-0.25,0.1,0.1,0.02, 0.3, 0.36, -0.9, 0.1] )
b14 = -0.1

# Create operations of first hidden layer and print
o11 = np.dot(x, w11) + b11
o12 = np.dot(x, w12) + b12
o13 = np.dot(x, w13) + b13
o14 = np.dot(x, w14) + b14
a1 = relu(np.array([o11, o12, o13, o14]))
print('Output from first hidden layer is : ', a1)

# Enter the weights and bias of output layer
w21 = np.array([-0.05,0.1,0.1,0.2])
b21 = 0

# Define the functionality of output layer and print the output
o21 = sigmoid(np.dot(a1, w21) + b21)
print('Final output is :', o21)


Output from first hidden layer is :  [0.795 0.038 0.905 0.   ]
Final output is : 0.5136341192441052


Q.10 What will be the output of the following code

In [27]:
x = tf.data.Dataset.range(5, 15)
y = tf.data.Dataset.range(-1, -50, -1)
zipped = tf.data.Dataset.zip((x,y))
b = zipped.batch(7)

for batch in b.take(4):
  print([i.numpy for i in batch])

[<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(7,), dtype=int64, numpy=array([ 5,  6,  7,  8,  9, 10, 11])>>, <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(7,), dtype=int64, numpy=array([-1, -2, -3, -4, -5, -6, -7])>>]
[<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=int64, numpy=array([12, 13, 14])>>, <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=int64, numpy=array([ -8,  -9, -10])>>]
